version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: stratcap
      POSTGRES_USER: stratcap
      POSTGRES_PASSWORD: stratcap123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - stratcap-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - stratcap-network

  # API Gateway
  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://stratcap:stratcap123@postgres:5432/stratcap
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-secret-key-here
      ENVIRONMENT: development
    depends_on:
      - postgres
      - redis
    networks:
      - stratcap-network
    volumes:
      - ./backend/api-gateway:/app

  # User Management Service
  user-management:
    build:
      context: ./backend/services/user-management
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://stratcap:stratcap123@postgres:5432/stratcap
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-secret-key-here
      ENVIRONMENT: development
    depends_on:
      - postgres
      - redis
    networks:
      - stratcap-network
    volumes:
      - ./backend/services/user-management:/app

  # Fund Management Service
  fund-management:
    build:
      context: ./backend/services/fund-management
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://stratcap:stratcap123@postgres:5432/stratcap
      REDIS_URL: redis://redis:6379
      ENVIRONMENT: development
    depends_on:
      - postgres
      - redis
    networks:
      - stratcap-network
    volumes:
      - ./backend/services/fund-management:/app

  # Data Ingestion Service
  data-ingestion:
    build:
      context: ./backend/services/data-ingestion
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://stratcap:stratcap123@postgres:5432/stratcap
      REDIS_URL: redis://redis:6379
      ENVIRONMENT: development
    depends_on:
      - postgres
      - redis
    networks:
      - stratcap-network
    volumes:
      - ./backend/services/data-ingestion:/app

  # Calculation Engine Service
  calculation-engine:
    build:
      context: ./backend/services/calculation-engine
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://stratcap:stratcap123@postgres:5432/stratcap
      REDIS_URL: redis://redis:6379
      ENVIRONMENT: development
    depends_on:
      - postgres
      - redis
    networks:
      - stratcap-network
    volumes:
      - ./backend/services/calculation-engine:/app

  # Workflow Engine Service
  workflow-engine:
    build:
      context: ./backend/services/workflow-engine
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://stratcap:stratcap123@postgres:5432/stratcap
      REDIS_URL: redis://redis:6379
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ENVIRONMENT: development
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - stratcap-network
    volumes:
      - ./backend/services/workflow-engine:/app

  # Reporting Service
  reporting:
    build:
      context: ./backend/services/reporting
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://stratcap:stratcap123@postgres:5432/stratcap
      REDIS_URL: redis://redis:6379
      ENVIRONMENT: development
    depends_on:
      - postgres
      - redis
    networks:
      - stratcap-network
    volumes:
      - ./backend/services/reporting:/app

  # Notification Service
  notification:
    build:
      context: ./backend/services/notification
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://stratcap:stratcap123@postgres:5432/stratcap
      REDIS_URL: redis://redis:6379
      ENVIRONMENT: development
    depends_on:
      - postgres
      - redis
    networks:
      - stratcap-network
    volumes:
      - ./backend/services/notification:/app

  # Kafka Message Queue
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - stratcap-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - stratcap-network

  # Frontend Development Server
  frontend:
    build:
      context: ./frontend/web-app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
    volumes:
      - ./frontend/web-app:/app
      - /app/node_modules
    networks:
      - stratcap-network

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@stratcap.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - stratcap-network

  # Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - stratcap-network

networks:
  stratcap-network:
    driver: bridge

volumes:
  postgres_data:
  kafka_data: